name: 'Postgis Setup'
description: 'Setup Postgis database for end-to-end testing of metacatalog'
author: 'mmaelicke'
branding:
  icon: 'database'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  # not sure if we even need this.
  pgsql_version:
    required: false
    default: '11'
    description: 'PostgreSQL version'
  pg_version:
    required: false
    default: '2.5'
    description: 'PostGIS version'
