name: Test

on: ['push']

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgis:
        image: postgis/postgis:10-2.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install depts
      run: pip install sqlalchemy psycopg2

    - name: Test
      run: python ./test.py
      env:
        POSTGRES_PORT: ${{ job.services.postgis.ports[5432] }}